using System.Collections.Generic;

namespace U.GeneratorService.Services
{
    public class FakeNames
    {
        public static IList<string> GetNames { get; } = new List<string>
        {
            "Chai",
            "Chang",
            "Aniseed Syrup",
            "Mishi Kobe Niku",
            "Ikura",
            "Queso Cabrales",
            "Konbu",
            "Tofu",
            "Genen Shouyu",
            "Pavlova",
            "Alice Mutton",
            "Carnarvon Tigers",
            "Sir Rodney's Scones",
            "Gustaf's Knäckebröd",
            "Tunnbröd",
            "Guaraná Fantástica",
            "Schoggi Schokolade",
            "Rössle Sauerkraut",
            "Thüringer Rostbratwurst",
            "Nord-Ost Matjeshering",
            "Gorgonzola Telino",
            "Mascarpone Fabioli",
            "Geitost",
            "Sasquatch Ale",
            "Steeleye Stout",
            "Inlagd Sill",
            "Gravad lax",
            "Côte de Blaye",
            "Chartreuse verte",
            "Boston Crab Meat",
            "Jack's New England Clam Chowder",
            "Singaporean Hokkien Fried Mee",
            "Ipoh Coffee",
            "Gula Malacca",
            "Rogede sild",
            "Spegesild",
            "Zaanse koeken",
            "Chocolade",
            "Maxilaku",
            "Valkoinen suklaa",
            "Manjimup Dried Apples",
            "Filo Mix",
            "Perth Pasties",
            "Tourtière",
            "Pâté chinois",
            "Gnocchi di nonna Alice",
            "Ravioli Angelo",
            "Escargots de Bourgogne",
            "Raclette Courdavault",
            "Camembert Pierrot",
            "Sirop d'érable",
            "Tarte au sucre",
            "Vegie-spread",
            "Wimmers gute Semmelknödel",
            "Louisiana Fiery Hot Pepper Sauce",
            "Louisiana Hot Spiced Okra",
            "Laughing Lumberjack Lager",
            "Scottish Longbreads",
            "Gudbrandsdalsost",
            "Outback Lager",
            "Flotemysost",
            "Mozzarella di Giovanni",
            "Röd Kaviar",
            "Longlife Tofu",
            "Rhönbräu Klosterbier",
            "Lakkalikööri",
            "Original Frankfurter grüne Soße",
        };
    }
}