// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using U.SubscriptionService.Persistance.Contexts;

namespace U.SubscriptionService.Persistance.Migrations
{
    [DbContext(typeof(SubscriptionContext))]
    partial class SubscriptionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("U.SubscriptionService.Domain.AllowedEvents", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Allowed")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserSubscriptionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserSubscriptionId");

                    b.ToTable("AllowedEvents");
                });

            modelBuilder.Entity("U.SubscriptionService.Domain.SignalRConnection", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConnectionId")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserSubscriptionId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "ConnectionId");

                    b.HasIndex("UserSubscriptionId");

                    b.ToTable("SignalRConnections","Subscriptions");
                });

            modelBuilder.Entity("U.SubscriptionService.Domain.UserSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("UserSubscription","Subscriptions");
                });

            modelBuilder.Entity("U.SubscriptionService.Domain.AllowedEvents", b =>
                {
                    b.HasOne("U.SubscriptionService.Domain.UserSubscription", null)
                        .WithMany("AllowedEvents")
                        .HasForeignKey("UserSubscriptionId");
                });

            modelBuilder.Entity("U.SubscriptionService.Domain.SignalRConnection", b =>
                {
                    b.HasOne("U.SubscriptionService.Domain.UserSubscription", null)
                        .WithMany("Connections")
                        .HasForeignKey("UserSubscriptionId");
                });

            modelBuilder.Entity("U.SubscriptionService.Domain.UserSubscription", b =>
                {
                    b.OwnsOne("U.Common.Subscription.Preferences", "Preferences", b1 =>
                        {
                            b1.Property<Guid>("UserSubscriptionId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("DoNotNotifyAnyoneAboutMyActivity")
                                .HasColumnType("boolean");

                            b1.Property<int>("MinimalImportancyLevel")
                                .HasColumnType("integer");

                            b1.Property<int>("NumberOfWelcomeMessages")
                                .HasColumnType("integer");

                            b1.Property<bool>("OrderByCreationTimeDescending")
                                .HasColumnType("boolean");

                            b1.Property<bool>("OrderByImportancyDescending")
                                .HasColumnType("boolean");

                            b1.Property<bool>("SeeReadNotifications")
                                .HasColumnType("boolean");

                            b1.Property<bool>("SeeUnreadNotifications")
                                .HasColumnType("boolean");

                            b1.HasKey("UserSubscriptionId");

                            b1.ToTable("UserSubscription");

                            b1.WithOwner()
                                .HasForeignKey("UserSubscriptionId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
