// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using U.NotificationService.Infrastructure.Contexts;

namespace U.NotificationService.Infrastructure.Migrations
{
    [DbContext(typeof(NotificationContext))]
    [Migration("20191201230543_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("U.NotificationService.Domain.Entities.Confirmation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ConfirmationDate");

                    b.Property<int>("ConfirmationType");

                    b.Property<Guid>("DeviceReceivedId");

                    b.Property<Guid>("NotificationId");

                    b.Property<Guid>("User");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.HasIndex("User");

                    b.ToTable("Notification_confirmation","Notifications");
                });

            modelBuilder.Entity("U.NotificationService.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("IntegrationEvent")
                        .IsRequired();

                    b.Property<Guid>("IntegrationEventId");

                    b.Property<int>("IntegrationEventType");

                    b.HasKey("Id");

                    b.ToTable("Notification","Notifications");
                });

            modelBuilder.Entity("U.NotificationService.Domain.Entities.Notification+UserBasedEventImportancy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Importancy");

                    b.Property<Guid?>("NotificationId");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.ToTable("UserBasedEventImportancy");
                });

            modelBuilder.Entity("U.NotificationService.Domain.Entities.Confirmation", b =>
                {
                    b.HasOne("U.NotificationService.Domain.Entities.Notification")
                        .WithMany("Confirmations")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("U.NotificationService.Domain.Entities.Notification+UserBasedEventImportancy", b =>
                {
                    b.HasOne("U.NotificationService.Domain.Entities.Notification")
                        .WithMany("Importancies")
                        .HasForeignKey("NotificationId");
                });
#pragma warning restore 612, 618
        }
    }
}
