// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using U.NotificationService.Infrastracture.Contexts;

namespace U.NotificationService.Migrations
{
    [DbContext(typeof(NotificationContext))]
    [Migration("20191028200431_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("U.EventBus.Events.IntegrationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.HasKey("Id");

                    b.ToTable("IntegrationEvent");
                });

            modelBuilder.Entity("U.NotificationService.Domain.Confirmation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ConfirmationDate");

                    b.Property<int>("ConfirmationType");

                    b.Property<Guid>("DeviceReceivedId");

                    b.Property<Guid>("NotificationId");

                    b.Property<Guid?>("NotificationId1");

                    b.Property<Guid>("User");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId1");

                    b.HasIndex("User");

                    b.ToTable("Notification_confirmation","Notifications");
                });

            modelBuilder.Entity("U.NotificationService.Domain.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<Guid>("IntegrationEventId");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationEventId");

                    b.ToTable("Notification","Notifications");
                });

            modelBuilder.Entity("U.NotificationService.Domain.Confirmation", b =>
                {
                    b.HasOne("U.NotificationService.Domain.Notification", "Notification")
                        .WithMany("Confirmations")
                        .HasForeignKey("NotificationId1");
                });

            modelBuilder.Entity("U.NotificationService.Domain.Notification", b =>
                {
                    b.HasOne("U.EventBus.Events.IntegrationEvent", "IntegrationEvent")
                        .WithMany()
                        .HasForeignKey("IntegrationEventId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
