using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using AutoFixture;
using U.Common.Miscellaneous;
using U.Common.Products;

namespace U.GeneratorService.Services
{
    public interface IProductGenerator
    {
        SmartProductDto GenerateFakeProduct();
    }

    [SuppressMessage("ReSharper", "UnusedMember.Global")]
    public class FakeProductGenerator : IProductGenerator
    {
        private readonly IFixture _fixture = new Fixture();

        private static IList<string> GetNames { get; } = new List<string>
        {
            "ChaiChai",
            "ChaiChang",
            "ChaiAniseed Syrup",
            "ChaiMishi Kobe Niku",
            "ChaiIkura",
            "ChaiQueso Cabrales",
            "ChaiKonbu",
            "ChaiTofu",
            "ChaiGenen Shouyu",
            "ChaiPavlova",
            "ChaiAlice Mutton",
            "ChaiCarnarvon Tigers",
            "ChaiSir Rodney's Scones",
            "ChaiGustaf's Knäckebröd",
            "ChaiTunnbröd",
            "ChaiGuaraná Fantástica",
            "ChaiSchoggi Schokolade",
            "ChaiRössle Sauerkraut",
            "ChaiThüringer Rostbratwurst",
            "ChaiNord-Ost Matjeshering",
            "ChaiGorgonzola Telino",
            "ChaiMascarpone Fabioli",
            "ChaiGeitost",
            "ChaiSasquatch Ale",
            "ChaiSteeleye Stout",
            "ChaiInlagd Sill",
            "ChaiGravad lax",
            "ChaiCôte de Blaye",
            "ChaiChartreuse verte",
            "ChaiBoston Crab Meat",
            "ChaiJack's New England Clam Chowder",
            "ChaiSingaporean Hokkien Fried Mee",
            "ChaiIpoh Coffee",
            "ChaiGula Malacca",
            "ChaiRogede sild",
            "ChaiSpegesild",
            "ChaiZaanse koeken",
            "ChaiChocolade",
            "ChaiMaxilaku",
            "ChaiValkoinen suklaa",
            "ChaiManjimup Dried Apples",
            "ChaiFilo Mix",
            "ChaiPerth Pasties",
            "ChaiTourtière",
            "ChaiPâté chinois",
            "ChaiGnocchi di nonna Alice",
            "ChaiRavioli Angelo",
            "ChaiEscargots de Bourgogne",
            "ChaiRaclette Courdavault",
            "ChaiCamembert Pierrot",
            "ChaiSirop d'érable",
            "ChaiTarte au sucre",
            "ChaiVegie-spread",
            "ChaiWimmers gute Semmelknödel",
            "ChaiLouisiana Fiery Hot Pepper Sauce",
            "ChaiLouisiana Hot Spiced Okra",
            "ChaiLaughing Lumberjack Lager",
            "ChaiScottish Longbreads",
            "ChaiGudbrandsdalsost",
            "ChaiOutback Lager",
            "ChaiFlotemysost",
            "ChaiMozzarella di Giovanni",
            "ChaiRöd Kaviar",
            "ChaiLonglife Tofu",
            "ChaiRhönbräu Klosterbier",
            "ChaiLakkalikööri",
            "ChaiOriginal Frankfurter grüne Soße",
            "ChaigrüneSunOriginal",
            "ChaigrüneMonOriginal",
            "ChaigrüneTueOriginal",
            "ChaigrüneWedOriginal",
            "ChaigrüneThuOriginal",
            "ChaigrüneFriOriginal",
            "ChaigrüneSatOriginal",
            "ChaigrüneSunOriginal",
            "ChaiMonOriginal",
            "ChaiTueOriginal",
            "ChaiWedOriginal",
            "ChaiThuOriginal",
            "ChaiFriOriginal",
            "ChaiSatOriginal",
            "Chai",
            "Chang",
            "Aniseed Syrup",
            "Mishi Kobe Niku",
            "Ikura",
            "Queso Cabrales",
            "Konbu",
            "Tofu",
            "Genen Shouyu",
            "Pavlova",
            "Alice Mutton",
            "Carnarvon Tigers",
            "Sir Rodney's Scones",
            "Gustaf's Knäckebröd",
            "Tunnbröd",
            "Guaraná Fantástica",
            "Schoggi Schokolade",
            "Rössle Sauerkraut",
            "Thüringer Rostbratwurst",
            "Nord-Ost Matjeshering",
            "Gorgonzola Telino",
            "Mascarpone Fabioli",
            "Geitost",
            "Sasquatch Ale",
            "Steeleye Stout",
            "Inlagd Sill",
            "Gravad lax",
            "Côte de Blaye",
            "Chartreuse verte",
            "Boston Crab Meat",
            "Jack's New England Clam Chowder",
            "Singaporean Hokkien Fried Mee",
            "Ipoh Coffee",
            "Gula Malacca",
            "Rogede sild",
            "Spegesild",
            "Zaanse koeken",
            "Chocolade",
            "Maxilaku",
            "Valkoinen suklaa",
            "Manjimup Dried Apples",
            "Filo Mix",
            "Perth Pasties",
            "Tourtière",
            "Pâté chinois",
            "Gnocchi di nonna Alice",
            "Ravioli Angelo",
            "Escargots de Bourgogne",
            "Raclette Courdavault",
            "Camembert Pierrot",
            "Sirop d'érable",
            "Tarte au sucre",
            "Vegie-spread",
            "Wimmers gute Semmelknödel",
            "Louisiana Fiery Hot Pepper Sauce",
            "Louisiana Hot Spiced Okra",
            "Laughing Lumberjack Lager",
            "Scottish Longbreads",
            "Gudbrandsdalsost",
            "Outback Lager",
            "Flotemysost",
            "Mozzarella di Giovanni",
            "Röd Kaviar",
            "Longlife Tofu",
            "Rhönbräu Klosterbier",
            "Lakkalikööri",
            "Original Frankfurter grüne Soße",
            "grüneSunOriginal",
            "grüneMonOriginal",
            "grüneTueOriginal",
            "grüneWedOriginal",
            "grüneThuOriginal",
            "grüneFriOriginal",
            "grüneSatOriginal",
            "grüneSunOriginal",
            "MonOriginal",
            "TueOriginal",
            "WedOriginal",
            "ThuOriginal",
            "FriOriginal",
            "SatOriginal",
            "KlosterbierChai",
            "KlosterbierChang",
            "KlosterbierAniseed Syrup",
            "KlosterbierMishi Kobe Niku",
            "KlosterbierIkura",
            "KlosterbierQueso Cabrales",
            "KlosterbierKonbu",
            "KlosterbierTofu",
            "KlosterbierGenen Shouyu",
            "KlosterbierPavlova",
            "KlosterbierAlice Mutton",
            "KlosterbierCarnarvon Tigers",
            "KlosterbierSir Rodney's Scones",
            "KlosterbierGustaf's Knäckebröd",
            "KlosterbierTunnbröd",
            "KlosterbierGuaraná Fantástica",
            "KlosterbierSchoggi Schokolade",
            "KlosterbierRössle Sauerkraut",
            "KlosterbierThüringer Rostbratwurst",
            "KlosterbierNord-Ost Matjeshering",
            "KlosterbierGorgonzola Telino",
            "KlosterbierMascarpone Fabioli",
            "KlosterbierGeitost",
            "KlosterbierSasquatch Ale",
            "KlosterbierSteeleye Stout",
            "KlosterbierInlagd Sill",
            "KlosterbierGravad lax",
            "KlosterbierCôte de Blaye",
            "KlosterbierChartreuse verte",
            "KlosterbierBoston Crab Meat",
            "KlosterbierJack's New England Clam Chowder",
            "KlosterbierSingaporean Hokkien Fried Mee",
            "KlosterbierIpoh Coffee",
            "KlosterbierGula Malacca",
            "KlosterbierRogede sild",
            "KlosterbierSpegesild",
            "KlosterbierZaanse koeken",
            "KlosterbierChocolade",
            "KlosterbierMaxilaku",
            "KlosterbierValkoinen suklaa",
            "KlosterbierManjimup Dried Apples",
            "KlosterbierFilo Mix",
            "KlosterbierPerth Pasties",
            "KlosterbierTourtière",
            "KlosterbierPâté chinois",
            "KlosterbierGnocchi di nonna Alice",
            "KlosterbierRavioli Angelo",
            "KlosterbierEscargots de Bourgogne",
            "KlosterbierRaclette Courdavault",
            "KlosterbierCamembert Pierrot",
            "KlosterbierSirop d'érable",
            "KlosterbierTarte au sucre",
            "KlosterbierVegie-spread",
            "KlosterbierWimmers gute Semmelknödel",
            "KlosterbierLouisiana Fiery Hot Pepper Sauce",
            "KlosterbierLouisiana Hot Spiced Okra",
            "KlosterbierLaughing Lumberjack Lager",
            "KlosterbierScottish Longbreads",
            "KlosterbierGudbrandsdalsost",
            "KlosterbierOutback Lager",
            "KlosterbierFlotemysost",
            "KlosterbierMozzarella di Giovanni",
            "KlosterbierRöd Kaviar",
            "KlosterbierLonglife Tofu",
            "KlosterbierRhönbräu Klosterbier",
            "KlosterbierLakkalikööri",
            "KlosterbierOriginal Frankfurter grüne Soße",
            "KlosterbiergrüneSunOriginal",
            "KlosterbiergrüneMonOriginal",
            "KlosterbiergrüneTueOriginal",
            "KlosterbiergrüneWedOriginal",
            "KlosterbiergrüneThuOriginal",
            "KlosterbiergrüneFriOriginal",
            "KlosterbiergrüneSatOriginal",
            "KlosterbiergrüneSunOriginal",
            "KlosterbierMonOriginal",
            "KlosterbierTueOriginal",
            "KlosterbierWedOriginal",
            "KlosterbierThuOriginal",
            "KlosterbierFriOriginal",
            "KlosterbierSatOriginal",
            "Crab Steeleye Stout",
            "Crab Inlagd Sill",
            "Crab Gravad lax",
            "Crab Côte de Blaye",
            "Crab Chartreuse verte",
            "Crab Boston Crab Meat",
            "Crab Jack's New England Clam Chowder",
            "Crab Singaporean Hokkien Fried Mee",
            "Crab Ipoh Coffee",
            "Crab Gula Malacca",
            "Crab Rogede sild",
            "Crab Spegesild",
            "Crab Zaanse koeken",
            "CCrab hocolade",
            "MCrabaxilaku",
            "ValkoCrabinen suklaa",
            "Manjimup CrabDried Apples",
        };

        public SmartProductDto GenerateFakeProduct()
        {
            var random = new Random();

            var fakeProduct = new SmartProductDto
            {
                Description = GetRandomizedDescription(),
                Height = random.Next(350),
                Width = random.Next(350),
                Length = random.Next(350),
                Weight = random.Next(1300),
                CategoryId = random.Next(1, GlobalConstants.SmartStoreSeededCategories + 1),
                Name = GetNames[random.Next(GetNames.Count)] + random.Next(int.MaxValue) + random.Next(int.MaxValue),
                ManufacturerId = random.Next(1, GlobalConstants.SmartStoreSeededManufacturers + 1),
                BarCode = _fixture.Create<string>(),
                IsAvailable = true,
                Price = random.Next(9999),
                StockQuantity = random.Next(550)
            };

            return fakeProduct;
        }

        private string GetRandomizedDescription()
        {
            var random = new Random();
            var descriptionLong = random.Next() % 5;

            var description = String.Empty;

            for (int i = 0; i < descriptionLong; i++)
            {
                description += GetNames[random.Next(GetNames.Count)] + ". ";
            }

            if (descriptionLong > 3)
            {
                description += GetNames[random.Next(GetNames.Count)] + "!";
            }

            else
            {
                description += GetNames[random.Next(GetNames.Count)] + "?";
            }

            return description;
        }
    }
}